name: Pull requests on develop

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v1
        # env:
        #   cache-name: cache-node-modules
        with:
          path: ~/.npm
          # key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            # ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci

      # analyse:
      #   name: Analyse code quality
      #   needs: build
      #   runs-on: ubuntu-latest
      #   strategy:
      #     fail-fast: false
      #     matrix:
      #       node-version: [8.x, 10.x, 12.x]
      #   steps:
      - name: Run lint
        run: npm run lint src/*
      - name: Run tests
        run: npm test
        env:
          CI: true
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
